# Generated by Django 5.2.12 on 2026-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    'data_type',
                    models.CharField(
                        choices=[
                            ('current', 'Current'),
                            ('minutely', 'Minutely'),
                            ('hourly', 'Hourly'),
                            ('daily', 'Daily'),
                        ],
                        max_length=10,
                    ),
                ),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('weather_data', models.JSONField()),
            ],
            options={
                'db_table': 'weather_cache',
                'indexes': [
                    models.Index(fields=['lat', 'lon', 'data_type', 'fetched_at'], name='weather_cache_lookup_idx')
                ],
            },
        )
    ]
